/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CotRouteImport } from './routes/cot'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptionTastytradeRouteImport } from './routes/option.tastytrade'
import { Route as OptionCmeRouteImport } from './routes/option.cme'
import { Route as OptionAlpacaRouteImport } from './routes/option.alpaca'
import { Route as KalshiBitcoinRouteImport } from './routes/kalshi.bitcoin'
import { Route as DomBtcRouteImport } from './routes/dom.btc'
import { Route as BotOrbRouteImport } from './routes/bot.orb'
import { Route as OptionUnusualBarchartRouteImport } from './routes/option.unusual.barchart'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CotRoute = CotRouteImport.update({
  id: '/cot',
  path: '/cot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionTastytradeRoute = OptionTastytradeRouteImport.update({
  id: '/option/tastytrade',
  path: '/option/tastytrade',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionCmeRoute = OptionCmeRouteImport.update({
  id: '/option/cme',
  path: '/option/cme',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionAlpacaRoute = OptionAlpacaRouteImport.update({
  id: '/option/alpaca',
  path: '/option/alpaca',
  getParentRoute: () => rootRouteImport,
} as any)
const KalshiBitcoinRoute = KalshiBitcoinRouteImport.update({
  id: '/kalshi/bitcoin',
  path: '/kalshi/bitcoin',
  getParentRoute: () => rootRouteImport,
} as any)
const DomBtcRoute = DomBtcRouteImport.update({
  id: '/dom/btc',
  path: '/dom/btc',
  getParentRoute: () => rootRouteImport,
} as any)
const BotOrbRoute = BotOrbRouteImport.update({
  id: '/bot/orb',
  path: '/bot/orb',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionUnusualBarchartRoute = OptionUnusualBarchartRouteImport.update({
  id: '/option/unusual/barchart',
  path: '/option/unusual/barchart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/bot/orb': typeof BotOrbRoute
  '/dom/btc': typeof DomBtcRoute
  '/kalshi/bitcoin': typeof KalshiBitcoinRoute
  '/option/alpaca': typeof OptionAlpacaRoute
  '/option/cme': typeof OptionCmeRoute
  '/option/tastytrade': typeof OptionTastytradeRoute
  '/option/unusual/barchart': typeof OptionUnusualBarchartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/bot/orb': typeof BotOrbRoute
  '/dom/btc': typeof DomBtcRoute
  '/kalshi/bitcoin': typeof KalshiBitcoinRoute
  '/option/alpaca': typeof OptionAlpacaRoute
  '/option/cme': typeof OptionCmeRoute
  '/option/tastytrade': typeof OptionTastytradeRoute
  '/option/unusual/barchart': typeof OptionUnusualBarchartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/bot/orb': typeof BotOrbRoute
  '/dom/btc': typeof DomBtcRoute
  '/kalshi/bitcoin': typeof KalshiBitcoinRoute
  '/option/alpaca': typeof OptionAlpacaRoute
  '/option/cme': typeof OptionCmeRoute
  '/option/tastytrade': typeof OptionTastytradeRoute
  '/option/unusual/barchart': typeof OptionUnusualBarchartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/bot/orb'
    | '/dom/btc'
    | '/kalshi/bitcoin'
    | '/option/alpaca'
    | '/option/cme'
    | '/option/tastytrade'
    | '/option/unusual/barchart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/bot/orb'
    | '/dom/btc'
    | '/kalshi/bitcoin'
    | '/option/alpaca'
    | '/option/cme'
    | '/option/tastytrade'
    | '/option/unusual/barchart'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/bot/orb'
    | '/dom/btc'
    | '/kalshi/bitcoin'
    | '/option/alpaca'
    | '/option/cme'
    | '/option/tastytrade'
    | '/option/unusual/barchart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CotRoute: typeof CotRoute
  HistoryRoute: typeof HistoryRoute
  NewsRoute: typeof NewsRoute
  OverviewRoute: typeof OverviewRoute
  BotOrbRoute: typeof BotOrbRoute
  DomBtcRoute: typeof DomBtcRoute
  KalshiBitcoinRoute: typeof KalshiBitcoinRoute
  OptionAlpacaRoute: typeof OptionAlpacaRoute
  OptionCmeRoute: typeof OptionCmeRoute
  OptionTastytradeRoute: typeof OptionTastytradeRoute
  OptionUnusualBarchartRoute: typeof OptionUnusualBarchartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot': {
      id: '/cot'
      path: '/cot'
      fullPath: '/cot'
      preLoaderRoute: typeof CotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option/tastytrade': {
      id: '/option/tastytrade'
      path: '/option/tastytrade'
      fullPath: '/option/tastytrade'
      preLoaderRoute: typeof OptionTastytradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option/cme': {
      id: '/option/cme'
      path: '/option/cme'
      fullPath: '/option/cme'
      preLoaderRoute: typeof OptionCmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option/alpaca': {
      id: '/option/alpaca'
      path: '/option/alpaca'
      fullPath: '/option/alpaca'
      preLoaderRoute: typeof OptionAlpacaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalshi/bitcoin': {
      id: '/kalshi/bitcoin'
      path: '/kalshi/bitcoin'
      fullPath: '/kalshi/bitcoin'
      preLoaderRoute: typeof KalshiBitcoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dom/btc': {
      id: '/dom/btc'
      path: '/dom/btc'
      fullPath: '/dom/btc'
      preLoaderRoute: typeof DomBtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/orb': {
      id: '/bot/orb'
      path: '/bot/orb'
      fullPath: '/bot/orb'
      preLoaderRoute: typeof BotOrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option/unusual/barchart': {
      id: '/option/unusual/barchart'
      path: '/option/unusual/barchart'
      fullPath: '/option/unusual/barchart'
      preLoaderRoute: typeof OptionUnusualBarchartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CotRoute: CotRoute,
  HistoryRoute: HistoryRoute,
  NewsRoute: NewsRoute,
  OverviewRoute: OverviewRoute,
  BotOrbRoute: BotOrbRoute,
  DomBtcRoute: DomBtcRoute,
  KalshiBitcoinRoute: KalshiBitcoinRoute,
  OptionAlpacaRoute: OptionAlpacaRoute,
  OptionCmeRoute: OptionCmeRoute,
  OptionTastytradeRoute: OptionTastytradeRoute,
  OptionUnusualBarchartRoute: OptionUnusualBarchartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
