/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CotRouteImport } from './routes/cot'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomBtcRouteImport } from './routes/dom.btc'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CotRoute = CotRouteImport.update({
  id: '/cot',
  path: '/cot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomBtcRoute = DomBtcRouteImport.update({
  id: '/dom/btc',
  path: '/dom/btc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/dom/btc': typeof DomBtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/dom/btc': typeof DomBtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cot': typeof CotRoute
  '/history': typeof HistoryRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/dom/btc': typeof DomBtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/dom/btc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/dom/btc'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/cot'
    | '/history'
    | '/news'
    | '/overview'
    | '/dom/btc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CotRoute: typeof CotRoute
  HistoryRoute: typeof HistoryRoute
  NewsRoute: typeof NewsRoute
  OverviewRoute: typeof OverviewRoute
  DomBtcRoute: typeof DomBtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cot': {
      id: '/cot'
      path: '/cot'
      fullPath: '/cot'
      preLoaderRoute: typeof CotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dom/btc': {
      id: '/dom/btc'
      path: '/dom/btc'
      fullPath: '/dom/btc'
      preLoaderRoute: typeof DomBtcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CotRoute: CotRoute,
  HistoryRoute: HistoryRoute,
  NewsRoute: NewsRoute,
  OverviewRoute: OverviewRoute,
  DomBtcRoute: DomBtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
